### PR TITLE
Additional fixes.

### PR DESCRIPTION
**Pull request by samdeane**
This is an evolution of the code in PR #34. We've had some crashes reported for Sketch using that code, so I've refined it further.

I still don't think I've got all the crashes out, so I will probably have to reinstate the JSValueProtect hack in the meantime.

Debugging this code is quite interesting though.

I've downgraded a couple of the assertions to just be debug() statements, and I get the "box should have been disassociated" one firing occasionally, seemingly when things are being cleaned up.

It looks like it's firing for something that was passed as a parameter in a function call, though I'm not 100% certain.

### CODE REVIEW

**Comment by samdeane** [comment]
(if we ever conclude that this code is good, I can make more of an attempt to factor it out into some more manageable PRs - for now this is mostly just FYI)

**Comment by ccgus** [comment]
Thanks- I'll take a look at this when I get a chance. I'd like to merge in all your changes as well- but there's some stuff that I need to sort through and figure out what's breaking Acorn.

**Comment by samdeane** [comment]
Sure - no hurry, and just yell if you need a hand disentangling our stuff :)

**Comment by samdeane** [comment]
Oops - this branch got deleted on our end, so the PR went away. I'll make another.

**Pull request closed without merging**
